Yodel.load_extension(File.join(File.dirname(__FILE__), 'administration'))
Yodel.load_extension(File.join(File.dirname(__FILE__), 'pages'))
Yodel.load_extension(File.join(File.dirname(__FILE__), 'blog'))
Yodel.load_extension(File.join(File.dirname(__FILE__), 'search'))
Yodel.load_extension(File.join(File.dirname(__FILE__), 'calendar'))
Yodel.load_extension(File.join(File.dirname(__FILE__), 'video'))
Yodel.load_extension(File.join(File.dirname(__FILE__), 'shop'))
#Yodel.load_extension(File.join(File.dirname(__FILE__), 'form_mailer'))
