require File.join(File.dirname(__FILE__), 'models', 'searchable')
require File.join(File.dirname(__FILE__), 'models', 'attachment')
require File.join(File.dirname(__FILE__), 'models', 'record')
require File.join(File.dirname(__FILE__), 'models', 'site')
require File.join(File.dirname(__FILE__), 'models', 'hierarchical')
